### ISSUE TITLE
Evaluate fluentd for log shipping

### ISSUE THREAD

**Issue by puja108** [giantswarm/kubernetes-elastic-stack#21]
Maybe only as an alternative. Would be good to also have the fluentd option not only because it's CNCF, but also cause people might want to ship logs to other datastores that are better supported by fluentd.

An example DS can be found here:
https://github.com/inovex/kubernetes-logging
and
http://logz.io/blog/kubernetes-log-analysis/

Tasks:
- [x] Create Fluentd Docker image
- [x] Create Kubernetes manifests
- [ ] Document configuration settings
- [ ] Document special config for Minikube

**Comment by puja108** [comment]
It seems that the logging roadmap is pretty much focussed on fluentd, we might miss out on functionality with another solution.

https://github.com/kubernetes/kubernetes/issues/17183

**Comment by webwurst** [comment]
Done via https://github.com/giantswarm/kubernetes-elastic-stack/pull/37.
