### ISSUE TITLE
Update #25 - Extra text in filebeat DaemonSet

### ISSUE THREAD

**Issue by xxzone** [giantswarm/kubernetes-elastic-stack#29]
It looks like there is extra text in the filebeat DamemonSet section of the manifests-all.yaml which causes the install to fail.

**Comment by webwurst** [comment]
Thanks! I will add some tests to this setup to catch errors like this in the future.

**Comment by xxzone** [comment]
Thanks for this. Your work is very appreciated. It's helped a ton.
