### ISSUE TITLE
/etc/systemd/system/docker.service: No such file or directory

### ISSUE THREAD

**Issue by Morriz** [giantswarm/kubernetes-elastic-stack#38]
I am using minikube 0.22.3 which does not use boot2docker.

**Comment by Morriz** [comment]
It is now found here: `/lib/systemd/system/docker.service`

**Comment by marians** [comment]
To be solved in #37

**Comment by webwurst** [comment]
Hi @Morriz! I just merged updates to use the elastic stack `v6.0.0` and added `fluentd` with addon to add Kubernetes meta data. With this there is no need for the hack around the Docker daemon. Please re-open if this still an issue for you.
