### ISSUE TITLE
Error "the API version in the data (batch/v2alpha1) does not match the expected API version (batch/v1beta1)"

### ISSUE THREAD

**Issue by michaelpietzsch** [giantswarm/kubernetes-elastic-stack#39]
The Yaml validation fails. 
error: error validating "https://raw.githubusercontent.com/giantswarm/kubernetes-elastic-stack/master/manifests-all.yaml": error validating data: the server could not find the requested resource; if you choose to ignore these errors, turn validation off with --validate=false

Error from server (BadRequest): error when creating "https://raw.githubusercontent.com/giantswarm/kubernetes-elastic-stack/master/manifests-all.yaml": the API version in the data (batch/v2alpha1) does not match the expected API version (batch/v1beta1)

I'm running Kubernetes 1.8.0

**Comment by webwurst** [comment]
@michaelpietzsch can you please re-test with our recent version upgrade? Works fine for me with current Minikube another cluster, both running Kubernetes 1.8.0.

**Comment by pipo02mix** [comment]
A bit out of date. Please reopen if it still have issues
